use serde_repr::{Deserialize_repr, Serialize_repr};

#[repr(u8)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum RuleType {
    TitleContains = 0,
    ContentContains = 1,
    AsnIs = 2,
    CorrespondentIs = 3,
    DocumentTypeIs = 4,
    IsInInbox = 5,
    HasTag = 6,
    HasAnyTag = 7,
    CreatedBefore = 8,
    CreatedAfter = 9,
    CreationYearIs = 10,
    CreationMonthIs = 11,
    CreationDayIs = 12,
    AddedBefore = 13,
    AddedAfter = 14,
    ModifiedBefore = 15,
    ModifiedAfter = 16,
    DoesNotHaveTag = 17,
    DoesNotHaveAsn = 18,
    TitleOrContentContains = 19,
    FulltextQuery = 20,
    MoreLikeThis = 21,
    HasTagsIn = 22,
    AsnGreaterThan = 23,
    AsnLesserThan = 24,
    StoragePathIs = 25,
    HasCorrespondentIn = 26,
    DoesNotHaveCorrespondentIn = 27,
    HasDocumentTypeIn = 28,
    DoesNotHaveDocumentTypeIn = 29,
    HasStoragePathIn = 30,
    DoesNotHaveStoragePathIn = 31,
    OwnerIs = 32,
    HasOwnerIn = 33,
    DoesNotHaveOwner = 34,
    DoesNotHaveOwnerIn = 35,
    HasCustomFieldValue = 36,
    IsSharedByMe = 37,
    HasCustomFields = 38,
    HasCustomFieldsIn = 39,
    DoesNotHaveCustomFieldsIn = 40,
    DoesNotHaveCustomFields = 41,
    CustomFieldsQuery = 42,
    CreatedTo = 43,
    CreatedFrom = 44,
    AddedTo = 45,
    AddedFrom = 46,
    MimeTypeIs = 47,
}
